/**
 * Every guidance illustration.
 *
 * GENERATED by shared/scripts/build-illustrations.mjs — do not edit.
 */
export {type IllustrationProps} from './base';
export * from './garment';
export * from './pose';
